# Generated by Django 3.2.8 on 2021-10-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bad_test_images',
            field=models.ImageField(blank=True, upload_to='bad_test_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='bad_training_images',
            field=models.ImageField(blank=True, upload_to='bad_training_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='bad_validation_images',
            field=models.ImageField(blank=True, upload_to='bad_validation_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='good_test_images',
            field=models.ImageField(blank=True, upload_to='good_test_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='good_training_images',
            field=models.ImageField(blank=True, upload_to='good_training_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='good_validation_images',
            field=models.ImageField(blank=True, upload_to='good_validation_pics'),
        ),
    ]
