# Generated by Django 3.2.8 on 2021-10-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0005_auto_20211029_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodTrainingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='good_training_images/')),
            ],
        ),
    ]
