# Generated by Django 3.2.8 on 2021-10-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0006_goodtrainingimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='author',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
