# Generated by Django 3.2.8 on 2021-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0007_auto_20211029_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadTestImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bad_test_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BadTrainingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bad_training_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BadValidationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bad_validation_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GoodTestImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='good_test_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GoodValidationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='good_validation_images/')),
            ],
        ),
    ]
