# Generated by Django 3.2.8 on 2021-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0008_badtestimages_badtrainingimages_badvalidationimages_goodtestimages_goodvalidationimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badtestimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Test/bad_test_images/'),
        ),
        migrations.AlterField(
            model_name='badtrainingimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Training/bad_training_images/'),
        ),
        migrations.AlterField(
            model_name='badvalidationimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Validation/bad_validation_images/'),
        ),
        migrations.AlterField(
            model_name='goodtestimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Test/good_test_images/'),
        ),
        migrations.AlterField(
            model_name='goodtrainingimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Training/good_training_images/'),
        ),
        migrations.AlterField(
            model_name='goodvalidationimages',
            name='image',
            field=models.ImageField(upload_to='MachineLearning/Validation/good_validation_images/'),
        ),
    ]
