# Generated by Django 3.2.8 on 2021-11-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0010_evaluateimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluateImage',
        ),
    ]
