# Generated by Django 3.2.8 on 2021-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0011_delete_evaluateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MachineLearning/Usertest')),
            ],
        ),
    ]
