# Generated by Django 3.2.8 on 2021-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0012_usertestimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MachineLearning/UserTest/Image/')),
            ],
        ),
    ]
