# Generated by Django 3.2.8 on 2021-12-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0013_loadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadCam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlmodel', models.FileField(default=None, upload_to='MachineLearning/UserTest/Model/')),
                ('camera', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTestImage',
        ),
    ]
