# Generated by Django 3.2.8 on 2021-12-03 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0014_auto_20211203_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcam',
            name='dlmodel',
            field=models.FileField(default=None, upload_to='MachineLearning/UserTest/Model/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['h5'])]),
        ),
    ]
