# Generated by Django 3.2.8 on 2021-12-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0015_alter_loadcam_dlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='bad_test_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='bad_training_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='bad_validation_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='good_test_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='good_training_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='good_validation_images',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bad_Test_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.badtestimages', verbose_name='Bad Test Images')),
                ('Bad_Training_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.badtrainingimages', verbose_name='Bad Training Images')),
                ('Bad_Validation_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.badvalidationimages', verbose_name='Bad Validation Images')),
                ('Good_Test_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.goodtestimages', verbose_name='Good Test Images')),
                ('Good_Training_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.goodtrainingimages', verbose_name='Good Training Images')),
                ('Good_Validation_Images', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.goodvalidationimages', verbose_name='Good Validation Images')),
            ],
            options={
                'verbose_name_plural': 'Post Images',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
    ]
