# Generated by Django 3.2.8 on 2021-12-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0016_auto_20211215_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_slug',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Bad_Test_Images',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Bad_Training_Images',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Bad_Validation_Images',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Good_Test_Images',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Good_Training_Images',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='Good_Validation_Images',
        ),
        migrations.AddField(
            model_name='badtestimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='badtestimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='badtrainingimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='badtrainingimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='badvalidationimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='badvalidationimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='goodtestimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='goodtestimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='goodtrainingimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='goodtrainingimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='goodvalidationimages',
            name='Post_Images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.postimages', verbose_name='Post Images'),
        ),
        migrations.AddField(
            model_name='goodvalidationimages',
            name='Post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='postimages',
            name='Post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
    ]
