# Generated by Django 3.2.8 on 2021-12-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0017_auto_20211215_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.RenameField(
            model_name='badtestimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RenameField(
            model_name='badtrainingimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RenameField(
            model_name='badvalidationimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RenameField(
            model_name='goodtestimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RenameField(
            model_name='goodtrainingimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RenameField(
            model_name='goodvalidationimages',
            old_name='Post_slug',
            new_name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
