# Generated by Django 3.2.8 on 2021-12-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0018_auto_20211215_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_slug',
        ),
    ]
