# Generated by Django 3.2.8 on 2021-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0019_remove_post_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badtestimages',
            name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='badtrainingimages',
            name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='badvalidationimages',
            name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='goodtestimages',
            name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='goodtrainingimages',
            name='Post_Images_slug',
        ),
        migrations.RemoveField(
            model_name='goodvalidationimages',
            name='Post_Images_slug',
        ),
    ]
