# Generated by Django 3.2.8 on 2021-12-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0020_auto_20211215_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badtestimages',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='badtrainingimages',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='badvalidationimages',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='goodtestimages',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='goodtrainingimages',
            name='Post_Images',
        ),
        migrations.RemoveField(
            model_name='goodvalidationimages',
            name='Post_Images',
        ),
        migrations.AddField(
            model_name='badtestimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='badtrainingimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='badvalidationimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='goodtestimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='goodtrainingimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='goodvalidationimages',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
