# Generated by Django 3.2.8 on 2021-12-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0021_auto_20211215_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodtrainingimages',
            old_name='post',
            new_name='reference_post',
        ),
    ]
