# Generated by Django 3.2.8 on 2021-12-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0022_rename_post_goodtrainingimages_reference_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bad_test_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bad_training_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bad_validation_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='good_test_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='good_training_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='good_validation_images',
        ),
    ]
