# Generated by Django 3.2.8 on 2021-12-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0023_auto_20211215_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtrainingimages',
            name='reference_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningWebsite.post', verbose_name='Post'),
        ),
    ]
