# Generated by Django 3.2.8 on 2021-12-16 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0025_auto_20211215_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmodel',
            name='dlmodel',
            field=models.FileField(default=None, upload_to='MachineLearning/UserTest/Model/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['h5'])]),
        ),
    ]
