# Generated by Django 3.2.8 on 2021-12-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0027_remove_loadmodel_dlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodtrainingimages',
            name='reference_post',
        ),
    ]
