# Generated by Django 3.2.8 on 2021-12-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningWebsite', '0028_remove_goodtrainingimages_reference_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badtestimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='badtrainingimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='badvalidationimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='goodtestimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='goodtrainingimages',
            name='author',
        ),
        migrations.RemoveField(
            model_name='goodvalidationimages',
            name='post',
        ),
    ]
